apiVersion: nodes.lailin.xyz/v1
kind: NodePool
metadata:
  name: master
spec:
#  taints:
#    - key: node-pool.lailin.xyz
#      value: master
#      effect: NoSchedule
  labels:
    "node-pool.lailin.xyz/master": "7"
  handler: runc
